---
global:
  timeout: 3
  storage:
    module: DBM_File
    file: /tmp/moxy.ndbm
    dbm_class: NDBM_File

plugins:
  - module: ControlPanel
  - module: XMLisHTML
  - module: UserAgentSwitcher
  - module: Pictogram
  - module: DisplayWidth
  - module: QRCode
  - module: RefererCutter
  - module: ShowHTTPHeaders
  - module: CookieCutter
  - module: HTTPHeader
  - module: FlashUseImgTag
  - module: DisableTableTag
  - module: GPS
# - module: QRCode::Imager
  - module: UserID
  - module: LocationBar

