--- 
abstract: ~
author: ~
build_requires: 
  Path::Class: 0
  Test::More: 0
  Web::Scraper: 0.24
distribution_type: module
generated_by: Module::Install version 0.68
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Moxy
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Encode::Detect: 1
  HTML::StickyQuery: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires: 
  CGI: 0
  Carp: 0
  Class::Accessor: 0
  FindBin: 0
  Getopt::Long: 0
  HTML::Entities::ImodePictogram: 0
  HTTP::MobileAgent: 0
  HTTP::Proxy: 0
  Log::Dispatch: 0
  Path::Class: 0
  Pod::Usage: 0
  Template: 0
  UNIVERSAL::require: 0
  YAML: 0
tests: t/*.t t/*/*.t t/*/*/*.t
version: 0.04
