---
abstract: 'Mobile web development proxy'
author:
  - 'Kan Fushihara'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moxy
no_index:
  directory:
    - inc
    - t
recommends:
  Encode::Detect: 1
  HTML::Scrubber: 1.04
  HTML::StripScripts: 1.04
  HTML::StripScripts::Parser: 1.02
requires:
  App::Cmd: 0.2
  Class::Accessor: 0
  Class::Component: 0.17
  Encode::JP::Mobile: 0.25
  Filter::Util::Call: 0
  HTML::ReplacePictogramMobileJp: 0.06
  HTML::Tree: 3.23
  HTML::TreeBuilder::XPath: 0.09
  HTTP::Cookies: 0
  HTTP::Engine: 0.1.4
  HTTP::MobileAttribute: 0.13
  HTTP::Session: 0.29
  Params::Validate: 0.91
  Path::Class: 0
  Template: 2.19
  UNIVERSAL::require: 0.11
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.coderepos.org/share/lang/perl/Moxy/trunk
version: 0.54
