--- 
abstract: Mobile web development proxy
author: 
  - Kan Fushihara
build_requires: 
  Path::Class: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.680
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Moxy
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Encode::Detect: 1
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires: 
  CGI: 0
  Carp: 0
  Class::Accessor: 0
  Class::Component: 0.16
  Encode::JP::Mobile: 0.22
  FindBin: 0
  HTML::ReplacePictogramMobileJp: 0.05
  HTML::Tree: 3.23
  HTTP::Engine: 0
  HTTP::MobileAttribute: 0
  HTTP::Proxy: 0
  Params::Validate: 0
  Path::Class: 0
  Template: 0
  UNIVERSAL::require: 0.11
tests: t/*.t t/*/*.t t/*/*/*.t
version: 0.32
